<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LFR035411" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2019-10-21T15:04:19 CEST" time="0.098" errors="0">
  <testcase name="test3" time="0.028" classname="util.RtryFail">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at util.RtryFail.test3(RtryFail.java:19)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.001" classname="util.RtryFail"/>
  <testcase name="test1" time="0.0" classname="util.RtryFail">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
